# Generated by Django 4.2.9 on 2024-01-23 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=30)),
                ('student_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=2)),
                ('birthdate', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('guardian', models.CharField(max_length=50, verbose_name='Guardian Name')),
                ('relationship', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50, verbose_name='Guardian Contact')),
                ('entry_year', models.IntegerField()),
                ('current_class', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.ImageField(upload_to='student_photos')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=10)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicclass')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
            options={
                'verbose_name': 'ClassRegister',
                'verbose_name_plural': 'ClassRegisters',
            },
        ),
    ]
