# Generated by Django 4.2.9 on 2024-01-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_classregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('reference_no', models.CharField(max_length=50)),
                ('recorded_by', models.CharField(max_length=50)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicclass', verbose_name='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student', verbose_name='')),
            ],
            options={
                'verbose_name': 'FeesPayment',
                'verbose_name_plural': 'FeesPayments',
            },
        ),
    ]
