# Generated by Django 4.2.9 on 2024-02-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feespayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
