# Generated by Django 4.2.9 on 2024-02-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stream_stream'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicclass',
            old_name='_class',
            new_name='Class',
        ),
    ]
