# Generated by Django 4.2.9 on 2024-02-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename__class_academicclass_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher', models.CharField(max_length=50)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicclass', verbose_name='')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='')),
            ],
            options={
                'verbose_name': 'ClassStream',
                'verbose_name_plural': 'ClassStreams',
            },
        ),
    ]
