# Generated by Django 4.2.9 on 2024-02-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_class_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
    ]
