# Generated by Django 4.2.9 on 2024-02-03 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_class_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.section', verbose_name=''),
            preserve_default=False,
        ),
    ]
