# Generated by Django 4.2.9 on 2024-02-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_academicyear_alter_section_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicclass',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear'),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.section'),
        ),
    ]
