# Generated by Django 4.2.9 on 2024-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_academicclass_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='UGX', max_length=10, unique=True)),
                ('desc', models.CharField(default='Ugandan Shillings', max_length=20)),
                ('cost', models.CharField(default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('UG', 'Uganda'), ('KE', 'Kenya'), ('TZ', 'Tanzania'), ('RD', 'Rwanda'), ('BD', 'Burundi'), ('SD', 'South Sudan')], default='Uganda', max_length=40)),
                ('city', models.CharField(default='Kampala', max_length=40)),
                ('address', models.CharField(default='None', max_length=50)),
                ('postal', models.CharField(default='None', max_length=50)),
                ('website', models.CharField(default='None', max_length=50)),
                ('school_name', models.CharField(default='None', max_length=50)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone_number1', models.CharField(blank=True, max_length=20, null=True)),
                ('office_phone_number2', models.CharField(blank=True, max_length=40, null=True)),
                ('school_logo', models.ImageField(upload_to='logo')),
                ('app_name', models.CharField(default='E-School', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='academicclass',
            options={'verbose_name': 'AcademicClass', 'verbose_name_plural': 'AcademicClasses'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream',
            field=models.CharField(default='-', max_length=10, unique=True),
        ),
    ]
