# Generated by Django 4.2.9 on 2024-06-12 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_academicclass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.section'),
            preserve_default=False,
        ),
    ]
