# Generated by Django 4.2.9 on 2024-06-21 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_academicclass_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClassStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_streams', to='app.academicclass')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream', verbose_name='')),
            ],
            options={
                'verbose_name': 'ClassStream',
                'verbose_name_plural': 'ClassStreams',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=50)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.RemoveField(
            model_name='classregister',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.AddField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.class', verbose_name='Current Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Burundi', 'Burundi')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Protestant', 'Protestant'), ('Catholic', 'Catholic'), ('Adventist', 'Adventist'), ('Others', 'Others')], max_length=30),
        ),
        migrations.DeleteModel(
            name='ClassStream',
        ),
        migrations.AlterField(
            model_name='classregister',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicclassstream'),
        ),
    ]
