# Generated by Django 4.2.9 on 2024-06-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_academicclassstream_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='school_motto',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
