# Generated by Django 4.2.9 on 2024-06-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_schoolsetting_school_motto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='entry_year',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('Current', 'Closed')], default='Current', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.academicyear', verbose_name='Entry Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicclassstream',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos'),
        ),
        migrations.AlterUniqueTogether(
            name='academicclassstream',
            unique_together={('academic_class', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='classregister',
            unique_together={('_class', 'student')},
        ),
    ]
