# Generated by Django 4.2.9 on 2024-06-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_student_entry_year_academicyear_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='status',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
