# Generated by Django 4.2.9 on 2024-06-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_academicyear_status_academicyear_is_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='_class',
            new_name='current_class',
        ),
        migrations.AlterField(
            model_name='classregister',
            name='payment_status',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
