# Generated by Django 4.2.9 on 2024-06-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_studentregistrationcsv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classregister',
            old_name='_class',
            new_name='academic_class_stream',
        ),
        migrations.AlterUniqueTogether(
            name='classregister',
            unique_together={('academic_class_stream', 'student')},
        ),
    ]
