# Generated by Django 4.2.9 on 2024-06-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename__class_classregister_academic_class_stream_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
