# Generated by Django 4.2.9 on 2024-07-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('marital_status', models.CharField(choices=[('M', 'Married'), ('U', 'Unmarried')], max_length=1)),
                ('contacts', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('department', models.CharField(choices=[('Student', 'Student'), ('Academic', 'Academic'), ('Finance', 'Finance'), ('Administration', 'Administration'), ('Security', 'Security'), ('Transport', 'Transport'), ('Support', 'Support')], max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff_status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Retired', 'Retired')], max_length=20)),
                ('staff_photo', models.ImageField(upload_to='Staff/Profile_pics')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='Staff/Documents')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'verbose_name': 'StaffDocument',
                'verbose_name_plural': 'StaffDocuments',
            },
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'verbose_name': 'bankdetail',
                'verbose_name_plural': 'bankdetails',
            },
        ),
    ]
