# Generated by Django 4.2.9 on 2024-07-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_billitem_payment_studentbill_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III')], max_length=5),
        ),
    ]
