# Generated by Django 4.2.9 on 2024-07-22 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_term_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.term'),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='bill_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('academic_year', 'term')},
        ),
        migrations.RemoveField(
            model_name='term',
            name='is_closed',
        ),
    ]
