# Generated by Django 4.2.9 on 2024-07-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='bill_duration',
            field=models.CharField(choices=[('None', 'None'), ('Termly', 'Termly'), ('Annually', 'Annually')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='billitem',
            name='category',
            field=models.CharField(choices=[('One Off', 'One Off'), ('Recurring', 'Recurring')], default='Recurring', max_length=50),
        ),
    ]
