# Generated by Django 4.2.9 on 2024-07-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_billitem_bill_duration_billitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbillitem',
            name='bill_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.billitem'),
            preserve_default=False,
        ),
    ]
