# Generated by Django 4.2.9 on 2024-07-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_studentbillitem_bill_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billitem',
            name='bill_duration',
            field=models.CharField(choices=[('None', 'None'), ('Termly', 'Termly'), ('Annually', 'Annually')], default='Termly', max_length=50),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='description',
            field=models.TextField(default='School Fees'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='item_name',
            field=models.CharField(default='School Fees', max_length=50),
        ),
    ]
