# Generated by Django 4.2.9 on 2024-07-27 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_billitem_bill_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentbill',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='term',
        ),
        migrations.AddField(
            model_name='studentbill',
            name='academic_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.academicclass'),
            preserve_default=False,
        ),
    ]
