# Generated by Django 4.2.9 on 2024-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_cashflowstatement_expense_incomesource_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='receipt',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
