# Generated by Django 4.2.9 on 2024-08-17 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_expenditure_receipt_expenditure_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.IntegerField()),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.expenditure')),
            ],
            options={
                'verbose_name': 'expenditureitem',
                'verbose_name_plural': 'expenditureitems',
            },
        ),
    ]
