# Generated by Django 4.2.9 on 2024-08-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_expenditureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureitem',
            name='units',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Set', 'Set'), ('Pair', 'Pair'), ('Box', 'Box'), ('Kgs', 'Kgs'), ('Litre', 'Litre'), ('Jerry Can', 'Jerry Can')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
