# Generated by Django 4.2.9 on 2024-08-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_expenditureitem_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='amount',
        ),
    ]
