# Generated by Django 4.2.9 on 2024-08-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_expenditure_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='contact_information',
            new_name='contact',
        ),
    ]
