# Generated by Django 4.2.9 on 2024-08-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_contact_information_vendor_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='expense',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_expenditures', to='app.budget'),
            preserve_default=False,
        ),
    ]
