# Generated by Django 4.2.9 on 2024-08-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_expenditure_expense_expenditure_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='department',
        ),
    ]
