# Generated by Django 4.2.9 on 2024-08-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_expenditure_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'budget', 'verbose_name_plural': 'budgets'},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='department',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.AddField(
            model_name='budget',
            name='academic_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.term'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='app.department')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='app.expense')),
            ],
        ),
    ]
