# Generated by Django 4.2.9 on 2024-08-24 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_budget_options_remove_budget_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='app.budget'),
            preserve_default=False,
        ),
    ]
