# Generated by Django 4.2.9 on 2024-08-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_budgetitem_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='budget',
            new_name='budget_item',
        ),
    ]
