# Generated by Django 4.2.9 on 2024-09-07 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rename_budget_expenditure_budget_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('-id',), 'verbose_name': 'budget', 'verbose_name_plural': 'budgets'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_department',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='related_vendor',
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='budget_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_expenditures', to='app.budgetitem'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('academic_year', 'term')},
        ),
    ]
