# Generated by Django 4.2.9 on 2024-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_bankaccount_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_academic_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_administrator_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_supportc_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
