# Generated by Django 4.2.9 on 2024-09-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_staff_is_academic_staff_staff_is_administrator_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='is_supportc_staff',
            new_name='is_support_staff',
        ),
    ]
