# Generated by Django 4.2.9 on 2024-09-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_rename_is_supportc_staff_staff_is_support_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicclassstream',
            name='class_teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.staff'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_class_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.academicclassstream')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.subject')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.staff')),
            ],
            options={
                'verbose_name': 'classsubjectallocation',
                'verbose_name_plural': 'classsubjectallocations',
            },
        ),
    ]
