# Generated by Django 4.2.9 on 2024-11-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_staffaccount_user'),
        ('app', '0052_assessment_assessmenttype_gradingsystem_termresult_and_more'),
    ]

    operations = [
    ]
