# Generated by Django 4.2.9 on 2024-12-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_academicyear_unique_current_academic_year'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicyear',
            name='unique_current_academic_year',
        ),
    ]
