# Generated by Django 4.2.9 on 2025-01-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_academicyear_unique_current_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('DOS', 'Director of Studies'), ('HEAD TEACHER', 'Headmaster'), ('CLASS TEACHER', 'Class Teacher')], max_length=50, unique=True),
        ),
    ]
