# Generated by Django 4.2.9 on 2025-01-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('bursar', 'Bursar'), ('director_of_studies', 'Director of Studies'), ('headmaster', 'Headmaster'), ('class_teacher', 'Class Teacher')], max_length=50, unique=True),
        ),
    ]
