# Generated by Django 4.2.9 on 2025-01-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='position',
            field=models.CharField(choices=[('HEAD TEACHER', 'HEAD TEACHER'), ('DIRECTOR OF STUDIES', 'DIRECTOR OF STUDIES'), ('CLASS TEACHER', 'CLASS TEACHER')], max_length=25),
        ),
    ]
