# Generated by Django 4.2.9 on 2025-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_signature_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicclassstream',
            options={'verbose_name': 'Class Stream', 'verbose_name_plural': 'Class Streams'},
        ),
        migrations.AddField(
            model_name='academicclassstream',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='class_teacher_signatures'),
        ),
    ]
