# Generated by Django 4.2.9 on 2025-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_academicclassstream_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicclassstream',
            old_name='signature',
            new_name='class_teacher_signature',
        ),
    ]
