# Generated by Django 4.2.9 on 2025-01-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_signature_academicclassstream_class_teacher_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicclassstream',
            name='class_teacher_signature',
        ),
    ]
