# Generated by Django 4.2.9 on 2025-03-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_academicclassstream_class_teacher_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_bills', to='app.academicclass'),
        ),
    ]
