# Generated by Django 4.2.9 on 2025-03-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_studentbill_academic_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='academic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicclass'),
        ),
    ]
