# Generated by Django 4.2.9 on 2025-03-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_studentbill_academic_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='app.academicclass')),
            ],
            options={
                'verbose_name': 'Class Bill Item',
                'verbose_name_plural': 'Class Bill Items',
            },
        ),
    ]
