# Generated by Django 4.2.9 on 2025-03-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_classbillitem_bill_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classbillitem',
            name='due_date',
        ),
    ]
