# Generated by Django 4.2.9 on 2025-03-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_classbillitem_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='app.academicclass')),
                ('bill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.billitem')),
            ],
        ),
        migrations.DeleteModel(
            name='ClassBillItem',
        ),
    ]
