# Generated by Django 4.2.9 on 2025-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_classbill_delete_classbillitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classbill',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classbill',
            unique_together={('academic_class', 'bill_item')},
        ),
    ]
