# Generated by Django 4.2.9 on 2025-03-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_classbill_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassBill',
        ),
    ]
