# Generated by Django 4.2.9 on 2025-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_classbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Rwanda', 'Rwanda'), ('South Sudan', 'South Sudan'), ('Burundi', 'Burundi'), ('Somali', 'Somali')], max_length=30),
        ),
    ]
