# Generated by Django 4.2.9 on 2025-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_student_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
