# Generated by Django 4.2.9 on 2025-03-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_payment_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Bursar', 'Bursar'), ('Director of Studies', 'Director of Studies'), ('Head master', 'Head master'), ('Class Teacher', 'Class Teacher')], max_length=50, unique=True),
        ),
    ]
