# Generated by Django 4.2.9 on 2025-03-18 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_role_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffaccount',
            unique_together=set(),
        ),
    ]
