# Generated by Django 4.2.9 on 2025-03-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_staffaccount_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='is_cumulative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='student_photos/default.jpg', null=True, upload_to='student_photos'),
        ),
    ]
