# Generated by Django 4.2.9 on 2025-03-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_assessmenttype_is_cumulative_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttype',
            name='is_cumulative',
        ),
    ]
