# Generated by Django 4.2.9 on 2025-03-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_assessmenttype_is_cumulative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(blank=True, default='Staff/Profile_pics/default.jpg', null=True, upload_to='Staff/Profile_pics'),
        ),
    ]
