# Generated by Django 4.2.9 on 2025-03-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_staff_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_photo',
            field=models.ImageField(default='', upload_to='Staff/Profile_pics'),
            preserve_default=False,
        ),
    ]
