# Generated by Django 4.2.9 on 2025-05-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_staff_staff_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditureitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
