# Generated by Django 4.2.9 on 2025-05-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_classroom_timeslot_timetable_breakperiod'),
        ('app', '0030_expenditure_vat_alter_expenditure_approved_by_and_more'),
    ]

    operations = [
    ]
