# Generated by Django 5.2.3 on 2025-07-03 07:53

from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Create model table only if it doesn't already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            if table_name in schema_editor.connection.introspection.table_names(cursor):
                return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class RemoveFieldIfExists(migrations.RemoveField):
    """Remove a field only when its database column exists."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = from_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        field = model._meta.get_field(self.name)
        column_name = field.column

        with schema_editor.connection.cursor() as cursor:
            if table_name not in schema_editor.connection.introspection.table_names(cursor):
                return
            existing_columns = {
                col.name
                for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }

        if column_name not in existing_columns:
            return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_reportresults_bot_remove_reportresults_eot_and_more'),
    ]

    operations = [
        CreateModelIfMissing(
            name='ResultModeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CUMULATIVE', 'Cumulative'), ('NON_CUMULATIVE', 'Non-Cumulative')], default='CUMULATIVE', max_length=20)),
            ],
        ),
        RemoveFieldIfExists(
            model_name='schoolsetting',
            name='assessment_method',
        ),
    ]
