# Generated by Django 5.2.3 on 2025-08-18 13:04

from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Add a field only when the target column is missing."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table
        field = model._meta.get_field(self.name)
        column_name = field.column

        with schema_editor.connection.cursor() as cursor:
            if table_name not in schema_editor.connection.introspection.table_names(cursor):
                return super().database_forwards(app_label, schema_editor, from_state, to_state)
            existing_columns = {
                col.name
                for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }

        if column_name in existing_columns:
            return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_schoolsetting_email'),
    ]

    operations = [
        AddFieldIfMissing(
            model_name='academicclassstream',
            name='class_teacher_signature',
            field=models.ImageField(default='', upload_to='signatures'),
            preserve_default=False,
        ),
    ]
