# Generated by Django 5.2.3 on 2025-08-24 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Create a model table only when it does not already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            if table_name in schema_editor.connection.introspection.table_names(cursor):
                return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_academicclassstream_class_teacher_signature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='position',
            field=models.CharField(choices=[('HEAD TEACHER', 'HEAD TEACHER'), ('DIRECTOR OF STUDIES', 'DIRECTOR OF STUDIES')], max_length=25),
        ),
        CreateModelIfMissing(
            name='ReportRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_remark', models.TextField(blank=True, null=True)),
                ('head_teacher_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='app.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='app.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
    ]
