# Generated by Django 5.2.3 on 2025-10-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_studentcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_slots', to='app.staff'),
        ),
    ]
