# Generated by Django 5.2.3 on 2025-10-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Create a model table only when it does not already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            if table_name in schema_editor.connection.introspection.table_names(cursor):
                return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_timetable_teacher'),
    ]

    operations = [
        CreateModelIfMissing(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_level', models.IntegerField(default=1)),
                ('max_approval_level', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenditures', to='app.staff')),
                ('current_approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to='app.staff')),
                ('expenditure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='app.expenditure')),
            ],
        ),
        CreateModelIfMissing(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='bank_statements/')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='app.bankaccount')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
        ),
        CreateModelIfMissing(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('reconciliation_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.bankstatement')),
                ('reconciled_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.payment')),
            ],
        ),
        CreateModelIfMissing(
            name='FeeAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule_type', models.CharField(choices=[('fee_update', 'Fee Structure Update'), ('discount_apply', 'Automatic Discount Application'), ('late_fee', 'Late Fee Assessment'), ('reminder_schedule', 'Reminder Schedule')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField()),
                ('actions', models.JSONField()),
                ('execution_schedule', models.CharField(blank=True, max_length=100, null=True)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
        ),
        CreateModelIfMissing(
            name='FinancialDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('dashboard_type', models.CharField(choices=[('summary', 'Financial Summary'), ('collection', 'Fee Collection'), ('expenditure', 'Expenditure Analysis'), ('budget', 'Budget Performance'), ('forecast', 'Financial Forecast')], max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
        ),
        CreateModelIfMissing(
            name='FinancialNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('overdue_notice', 'Overdue Notice'), ('fee_deadline', 'Fee Deadline'), ('budget_alert', 'Budget Alert'), ('expenditure_approval', 'Expenditure Approval Required'), ('bank_reconciliation', 'Bank Reconciliation Required')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_notifications', to='app.student')),
            ],
        ),
    ]
