# Generated by Django 5.2.3 on 2025-11-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_approvalworkflow_bankstatement_banktransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsystem',
            name='grade',
            field=models.CharField(max_length=10),
        ),
    ]
