# Generated by Django 5.2.3 on 2025-12-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    """Create a model table only when it does not already exist."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            if table_name in schema_editor.connection.introspection.table_names(cursor):
                return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_student_is_active'),
    ]

    operations = [
        CreateModelIfMissing(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.student')),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
