# Generated by Django 5.2.3 on 2025-12-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_studentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='bill_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.studentbill')),
            ],
            options={
                'verbose_name': 'Bill Document',
                'verbose_name_plural': 'Bill Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
