# Generated by Django 5.2.3 on 2025-12-24 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_billdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.studentbill'),
        ),
        migrations.DeleteModel(
            name='BillDocument',
        ),
    ]
