# Generated by Django 5.2.3 on 2025-12-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_studentdocument_bill_delete_billdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdocument',
            name='document_type',
            field=models.CharField(choices=[('IDENTITY', 'Identity / National ID'), ('ADMISSION', 'Admission Letter'), ('REPORT_CARD', 'Report Card'), ('TRANSCRIPT', 'Transcript'), ('CERTIFICATE', 'Certificate'), ('FEE_RECEIPT', 'Fee Receipt'), ('MEDICAL', 'Medical Document'), ('DISCIPLINE', 'Disciplinary Document'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('IDENTITY', 'Identity / National ID'), ('ADMISSION', 'Admission Letter'), ('REPORT_CARD', 'Report Card'), ('TRANSCRIPT', 'Transcript'), ('CERTIFICATE', 'Certificate'), ('FEE_RECEIPT', 'Fee Receipt'), ('MEDICAL', 'Medical Document'), ('DISCIPLINE', 'Disciplinary Document'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
