# Generated by Django 5.2.3 on 2025-12-26 16:09

import app.models.staffs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_staff_nin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='nin_no',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[app.models.staffs.validate_nin], verbose_name='NIN'),
        ),
    ]
