# Generated by Django 4.2.9 on 2026-01-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_staff_nin_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicclassstream',
            name='class_teacher_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures'),
        ),
    ]
