# Generated by Django 5.2.3 on 2026-02-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_result_verification_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultbatch',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
