# Generated by Django 5.2.3 on 2026-02-05 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_resultbatch_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultVerificationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_scripts', models.PositiveIntegerField(default=0)),
                ('sampled_count', models.PositiveIntegerField(default=0)),
                ('reentered_count', models.PositiveIntegerField(default=0)),
                ('matches_count', models.PositiveIntegerField(default=0)),
                ('mismatches_count', models.PositiveIntegerField(default=0)),
                ('corrections_count', models.PositiveIntegerField(default=0)),
                ('accuracy_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECHECK', 'Re-check Required')], default='RECHECK', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('sampling_method', models.CharField(default='Random (system)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_report', to='app.resultbatch')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_logs', to='app.resultbatch')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_corrections', to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_logs', to='app.result')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('verifier_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=6)),
                ('corrected_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('action_taken', models.CharField(default='Flagged', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='app.resultbatch')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='app.result')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy', to='app.verificationsample')),
            ],
        ),
    ]
