# Generated by Django 4.2.9 on 2026-02-10 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_resultverificationreport_verificationcorrectionlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All Staff'), ('teachers', 'Teachers'), ('head', 'Head Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher')], default='all', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('all', 'All Staff'), ('teachers', 'Teachers'), ('head', 'Head Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher')], default='all', max_length=20)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_datetime', 'title'],
            },
        ),
    ]
