# Generated by Django 4.2.9 on 2026-02-11 14:07

from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Add a field only when the DB column/through-table is missing."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        field = model._meta.get_field(self.name)

        with schema_editor.connection.cursor() as cursor:
            existing_tables = set(schema_editor.connection.introspection.table_names(cursor))

            # For M2M fields, Django creates an intermediate table.
            if field.many_to_many:
                through_table = field.remote_field.through._meta.db_table
                if through_table in existing_tables:
                    return
                return super().database_forwards(app_label, schema_editor, from_state, to_state)

            table_name = model._meta.db_table
            if table_name not in existing_tables:
                return super().database_forwards(app_label, schema_editor, from_state, to_state)

            column_name = field.column
            existing_columns = {
                col.name
                for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }

        if column_name in existing_columns:
            return

        return super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_message_thread_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time', 'end_time', 'id']},
        ),
        AddFieldIfMissing(
            model_name='schoolsetting',
            name='division_critical_subjects',
            field=models.ManyToManyField(blank=True, help_text="Subjects that can lower a student's division if grade is F9.", related_name='division_critical_for', to='app.subject'),
        ),
        AddFieldIfMissing(
            model_name='schoolsetting',
            name='division_f9_cap',
            field=models.CharField(default='Division 3', help_text='Maximum division allowed when a critical subject has F9 (e.g., Division 2 or Division 3).', max_length=12),
        ),
    ]
