# Generated by Django 4.2.9 on 2026-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_unique_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('method', models.CharField(choices=[('local-file', 'Local File'), ('mysql-native', 'MySQL Native'), ('hybrid', 'Hybrid (JSON + Native)')], default='hybrid', max_length=30)),
                ('schedule', models.CharField(default='daily 02:00', max_length=100)),
                ('backup_dir', models.CharField(default='backups', max_length=255)),
                ('max_age_hours', models.PositiveIntegerField(default=48)),
                ('retention_days', models.PositiveIntegerField(default=14)),
                ('include_media', models.BooleanField(default=False)),
                ('compress_backups', models.BooleanField(default=True)),
                ('mysqldump_bin', models.CharField(default='mysqldump', max_length=255)),
                ('last_manual_backup_at', models.DateTimeField(blank=True, null=True)),
                ('last_manual_backup_status', models.CharField(blank=True, default='', max_length=255)),
                ('last_manual_backup_path', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Configuration',
                'verbose_name_plural': 'Backup Configuration',
            },
        ),
    ]
