# Generated by Django 4.2.9 on 2026-02-26 07:02

from django.db import migrations, models


def forwards_normalize_backup_method(apps, schema_editor):
    BackupConfiguration = apps.get_model("app", "BackupConfiguration")
    db_alias = schema_editor.connection.alias
    BackupConfiguration.objects.using(db_alias).filter(method="local-file").update(method="json")
    BackupConfiguration.objects.using(db_alias).filter(method="mysql-native").update(method="native")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_normalize_backup_status_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupconfiguration',
            name='database_alias',
            field=models.CharField(default='default', help_text='Django DATABASES alias to back up/restore.', max_length=100),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='pg_dump_bin',
            field=models.CharField(default='pg_dump', max_length=255),
        ),
        migrations.AddField(
            model_name='backupconfiguration',
            name='psql_bin',
            field=models.CharField(default='psql', max_length=255),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='database_alias',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
        migrations.RunPython(
            forwards_normalize_backup_method,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='backupconfiguration',
            name='method',
            field=models.CharField(choices=[('json', 'JSON Export'), ('native', 'Database Native Dump'), ('hybrid', 'Hybrid (JSON + Native)')], default='hybrid', max_length=30),
        ),
    ]
