# Generated by Django 4.2.9 on 2026-02-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_move_secondary_models_to_secondary_app_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='education_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY_LOWER', 'Secondary (Lower)')], default='PRIMARY', help_text='Controls whether the system operates as primary or lower-secondary.', max_length=30),
        ),
    ]
