# Generated by Django 4.2.9 on 2026-02-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_schoolsetting_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetting',
            name='education_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY_LOWER', 'Secondary (O-Level)'), ('SECONDARY_UPPER', 'Secondary (A-Level)')], default='PRIMARY', help_text='Controls whether the system operates as primary or lower-secondary.', max_length=30),
        ),
    ]
