# Generated by Django 4.2.9 on 2026-02-27 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0073_normalize_schoolsetting_default_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('unlocked', 'Unlocked'), ('relocked', 'Relocked'), ('record_updated', 'Record Updated'), ('policy_updated', 'Policy Updated')], max_length=40)),
                ('old_status', models.CharField(blank=True, default='', max_length=20)),
                ('new_status', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_attendance_percent', models.PositiveSmallIntegerField(default=75)),
                ('allow_teacher_edit_locked_sessions', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Policy',
                'verbose_name_plural': 'Attendance Policy',
            },
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='app_attenda_status_5eeb61_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'session'], name='app_attenda_student_1eb506_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date', 'time_slot'], name='app_attenda_date_62a078_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['teacher', 'date'], name='app_attenda_teacher_aa82d4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['academic_year', 'term'], name='app_attenda_academi_857e93_idx'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='app.attendancerecord'),
        ),
        migrations.AddField(
            model_name='attendanceauditlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='app.attendancesession'),
        ),
        migrations.AddIndex(
            model_name='attendanceauditlog',
            index=models.Index(fields=['action', 'created_at'], name='app_attenda_action_a4602c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceauditlog',
            index=models.Index(fields=['session', 'created_at'], name='app_attenda_session_178704_idx'),
        ),
    ]
