# Generated by Django 4.2.9 on 2026-02-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_timetable_allocation_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicclassstream",
            name="is_timetable_locked",
            field=models.BooleanField(default=False),
        ),
    ]
