# Generated by Django 5.2.1 on 2026-02-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0079_hr_foundation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-year", "-month", "-id"),
                "constraints": [
                    models.UniqueConstraint(fields=("year", "month"), name="uniq_payroll_run_year_month"),
                    models.CheckConstraint(
                        check=models.Q(month__gte=1) & models.Q(month__lte=12),
                        name="payroll_run_month_valid_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("basic_salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("allowances_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("deductions_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("gross_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("net_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("is_paid", models.BooleanField(default=False)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=80)),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payroll_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="app.payrollrun",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_lines",
                        to="app.staff",
                    ),
                ),
            ],
            options={
                "ordering": ("staff__first_name", "staff__last_name", "id"),
                "indexes": [
                    models.Index(fields=["payroll_run", "is_paid"], name="app_payrolll_payroll_f8e3c9_idx"),
                    models.Index(fields=["staff", "payroll_run"], name="app_payrolll_staff_i_998675_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("payroll_run", "staff"), name="uniq_staff_per_payroll_run")
                ],
            },
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[("allowance", "Allowance"), ("deduction", "Deduction")],
                        max_length=20,
                    ),
                ),
                ("component_name", models.CharField(max_length=80)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payroll_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payroll_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="app.payrollline",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["payroll_line", "adjustment_type"],
                        name="app_payrolla_payroll_191d7b_idx",
                    )
                ],
            },
        ),
    ]
