# Generated by Django 4.2.9 on 2026-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_hr_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='app_employm_staff_i_c94cc0_idx',
            old_name='app_employme_staff_i_e98eaf_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='app_employm_status_eac3b4_idx',
            old_name='app_employme_status_c9a6aa_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='app_employm_effecti_7334b3_idx',
            old_name='app_employme_effecti_93237b_idx',
        ),
        migrations.RenameIndex(
            model_name='employmentrecord',
            new_name='app_employm_staff_i_d3fad1_idx',
            old_name='app_employme_staff_i_19f44b_idx',
        ),
        migrations.RenameIndex(
            model_name='staffhrdocument',
            new_name='app_staffhr_staff_i_3a937c_idx',
            old_name='app_staffhrd_staff_i_2925d4_idx',
        ),
        migrations.RenameIndex(
            model_name='staffhrdocument',
            new_name='app_staffhr_visibil_512be9_idx',
            old_name='app_staffhrd_visibil_7ab441_idx',
        ),
        migrations.RenameIndex(
            model_name='staffhrdocument',
            new_name='app_staffhr_expires_b8e3b1_idx',
            old_name='app_staffhrd_expires_1531f2_idx',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR Manager', 'HR Manager'), ('HR Officer', 'HR Officer'), ('Teacher', 'Teacher'), ('Bursar', 'Bursar'), ('Director of Studies', 'Director of Studies'), ('Head master', 'Head master'), ('Class Teacher', 'Class Teacher'), ('Support Staff', 'Support Staff')], max_length=50, unique=True),
        ),
    ]
