# Generated by Django 5.2.1 on 2026-02-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0080_payroll_core"),
        (
            "app",
            "0080_rename_app_employme_staff_i_e98eaf_idx_app_employm_staff_i_c94cc0_idx_and_more",
        ),
    ]

    operations = []
