# Generated by Django 4.2.9 on 2026-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_merge_20260228_0001'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payrolladjustment',
            new_name='app_payroll_payroll_dbbe25_idx',
            old_name='app_payrolla_payroll_191d7b_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollline',
            new_name='app_payroll_payroll_683224_idx',
            old_name='app_payrolll_payroll_f8e3c9_idx',
        ),
        migrations.RenameIndex(
            model_name='payrollline',
            new_name='app_payroll_staff_i_7c3170_idx',
            old_name='app_payrolll_staff_i_998675_idx',
        ),
    ]
