# Generated by Django 4.2.9 on 2026-02-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_normalize_staff_id_format"),
        ("app", "0082_rename_app_payrolla_payroll_191d7b_idx_app_payroll_payroll_dbbe25_idx_and_more"),
    ]

    operations = []
