# Generated by Django 4.2.9 on 2026-03-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_student_promotion_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmenttype',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
