# Generated by Django 4.2.9 on 2026-03-01 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_tenant_billing_status(apps, schema_editor):
    Tenant = apps.get_model("app", "Tenant")
    for tenant in Tenant.objects.all().only(
        "id",
        "lifecycle_status",
        "trial_ends_at",
        "billing_status",
        "next_billing_due_at",
    ):
        lifecycle = (tenant.lifecycle_status or "").upper()
        if lifecycle == "TERMINATED":
            billing_status = "CANCELED"
        elif lifecycle == "SUSPENDED":
            billing_status = "SUSPENDED"
        elif lifecycle == "GRACE":
            billing_status = "GRACE"
        elif lifecycle == "TRIAL":
            billing_status = "TRIAL"
        else:
            billing_status = "CURRENT"

        updates = {"billing_status": billing_status}
        if billing_status == "TRIAL" and tenant.trial_ends_at and not tenant.next_billing_due_at:
            updates["next_billing_due_at"] = tenant.trial_ends_at
        Tenant.objects.filter(pk=tenant.pk).update(**updates)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0089_tenant_lifecycle_status_tenant_suspended_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INVOICE_ISSUED', 'Invoice Issued'), ('PAYMENT_SUCCEEDED', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_RETRY', 'Payment Retry'), ('REFUND_ISSUED', 'Refund Issued'), ('PLAN_CHANGED', 'Plan Changed'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment')], max_length=40)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('reference', models.CharField(blank=True, default='', max_length=140)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_tenant_billing_event',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_grace_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('CURRENT', 'Current'), ('PAST_DUE', 'Past Due'), ('GRACE', 'Grace'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled')], default='TRIAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_billing_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['billing_status'], name='tenant_billing_status_idx'),
        ),
        migrations.AddField(
            model_name='tenantbillingevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_billing_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantbillingevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_events', to='app.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenantbillingevent',
            index=models.Index(fields=['tenant', 'created_at'], name='tenant_bill_evt_tc_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbillingevent',
            index=models.Index(fields=['event_type'], name='tenant_bill_event_type_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantbillingevent',
            index=models.Index(fields=['status'], name='tenant_bill_event_status_idx'),
        ),
        migrations.RunPython(backfill_tenant_billing_status, noop_reverse),
    ]
