# Generated by Django 4.2.9 on 2026-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_remove_payrolladjustment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Bursar', 'Bursar'), ('Director of Studies', 'Director of Studies'), ('Head master', 'Head master'), ('Class Teacher', 'Class Teacher'), ('Support Staff', 'Support Staff')], max_length=50, unique=True),
        ),
    ]
