# Generated by Django 4.2.9 on 2026-03-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_reconcile_student_promotion_history_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fee_category',
            field=models.CharField(blank=True, choices=[('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Uniform', 'Uniform'), ('Other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentbillitem',
            name='charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentbillitem',
            name='fee_category',
            field=models.CharField(choices=[('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Uniform', 'Uniform'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='studentbillitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='category',
            field=models.CharField(choices=[('One Off', 'One Off'), ('Recurring', 'Recurring'), ('Tuition', 'Tuition'), ('Transport', 'Transport'), ('Uniform', 'Uniform'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('SchoolPay', 'SchoolPay'), ('Bank', 'Bank'), ('Other', 'Other')], max_length=50),
        ),
    ]
