"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from decouple import config

import sys
import pymysql
pymysql.install_as_MySQLdb()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'app',
   
] 

CRISPY_TEMPLATE_PACK = "bootstrap5"
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.request_user.RequestUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware.update_jazzmin.UpdateJazzminMiddleware',
    'core.middleware.AutoLogoutMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.school_settings'
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'schooldb',
#         'USER': 'schooluser',
#         'PASSWORD': 'root@admin',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': config('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
        } if config('DB_ENGINE', default='django.db.backends.sqlite3') != 'django.db.backends.sqlite3' else {},
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': str(BASE_DIR / 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='Africa/Kampala')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')  
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = 'login'


#Ssessions
SESSION_COOKIE_AGE = 1800  # 30 minutes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  


DEV_TUNNEL_URL = "https//:bayan-learningcenter.com"  

# Email Configuration for SMTP (Using Gmail)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'webmaster@localhost')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'ERROR',
        },
        'file':{
            'class': 'logging.FileHandler',
            'filename': 'general.log',
            'formatter': 'verbose',
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
        }
    },
    'loggers':{
        '': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO')
        },
        'django.server': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        }
    },
    'formatters':{
        'verbose': {
            'format': '{asctime} ({levelname}) - {name} {message}',
            'style': '{' #str.format
        }
    }
    
}

USER_ROLE_PREFIXES = {
    'Admin': 'Admin-',
    'Teacher': 'Teacher-',
    'Bursar': 'bursar-',
    'Director of studies': 'Dos-',
    'Head master': 'Hm-',
    'class Teacher': 'Class-Teacher-',
}



# admin dashboard settings
JAZZMIN_SETTINGS = {
    "site_title": "Bayan Learning Center Admin",
    "site_header": "Bayan Learning Center Administration",
    "site_brand": "Bayan Learning Center",
    "custom_css": "css/rainbow.css",  # Overridden per-request by UpdateJazzminMiddleware
    "site_logo": "images/user.png",
    "site_logo_classes": "brand-image img-circle elevation-3",
    "site_icon": "images/favicon.ico",
    "welcome_sign": "Welcome to Bayan Learning Center Admin",
    "copyright": "UgaCloud 2025",
   

    # Quick global search
    "search_model": ["auth.User", "auth.Group"],

    # Navigation
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"app": "app"},
        {"model": "auth.User"},
        {"name": "WebApp", "url": "https://bayan-learningcenter.com", "icon": "fas fa-globe", "new_window": True},
    ],
    

    # Icons to improve scannability
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
    },

    # Forms and relations UX
    "related_modal_active": True,
    "changeform_format": "vertical_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible"},

    # Language / misc
    "language_chooser": False,
    "show_ui_builder": False,  # keep off in production

    # Dashboard recent actions
    "recent_actions": {
        "icon": "fas fa-history",
        "title": "Recent Activities",
        "card_class": "card-primary",
        "show_scroll_bar": True,
    },

    # Non-intrusive overrides (served via {% static %})
    # "custom_css": "css/custom_overrides.css",
    # "custom_js": "build/js/custom.js",
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",                     # Base theme (light)
    "dark_mode_theme": None,
    "theme_condition": "always",

    # Layout
    "navbar": "navbar-primary navbar-dark",   # Dark blue top bar
    "sidebar": "sidebar-dark-primary",        # Dark sidebar (deep blue)
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "actions_sticky_top": True,

    # Buttons
    "button_classes": {
        "primary": "btn btn-primary",
        "secondary": "btn btn-outline-secondary",
        "info": "btn btn-info",
        "warning": "btn btn-warning",
        "danger": "btn btn-danger",
        "success": "btn btn-success",
    },

    # UX polish
    "body_small_text": False,
    "brand_small_text": False,
    "sidebar_nav_small_text": False,
    "no_navbar_border": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_child_indent": True,
}
